# Generated by Django 3.0.8 on 2021-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210520_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
