# Generated by Django 3.0.8 on 2021-05-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210518_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
